apiVersion: v1
kind: Service
metadata:
  name: aegisops-service
  namespace: aegisops
  labels:
    app: aegisops
spec:
  selector:
    app: aegisops
  ports:
  - name: http
    port: 80
    targetPort: 5000