apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aegisops-app
  namespace: aegisops
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: aegisops
  namespaceSelector:
    matchNames:
    - aegisops
  endpoints:
  - port: http
    path: /metrics
    interval: 15s